DROP TABLE IF EXISTS whiskey;

CREATE TABLE whiskey(
	id INTEGER PRIMARY KEY,
	name TEXT UNIQUE,
	type TEXT,
	price INTEGER,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);